name: Cleanup PRs
description: Cleanup PRs that have been not updated
inputs:
  github-token:  # id of input
    description: GitHub Token
    required: true
runs:
  using: node16
  main: dist/index.js